version: "3"
services:
    loki:
        image: grafana/loki
        ports:
          - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        networks:
          - grafana-loki
    promtail:
        depends_on:
            - loki
        image: grafana/promtail
        volumes:
            - /var/log:/var/log
            - ./promtail:/etc/promtail
        command: -config.file=/etc/promtail/config.yml
        networks:
          - grafana-loki
    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        command: >-
            --config.file=/etc/prometheus/prometheus.yml
            --storage.tsdb.path=/prometheus
            --web.console.libraries=/usr/share/prometheus/console_libraries
            --web.console.templates=/usr/share/prometheus/consoles
        networks:
          - grafana-loki
    grafana:
        depends_on:
            - loki
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: test
            GF_PATHS_PROVISIONING: '/app.cfg/provisioning'
        volumes:
            - ./grafana:/app.cfg
        networks:
          - grafana-loki
networks:
  grafana-loki:
