server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://ec2-instance-ip:3100/loki/api/v1/push

scrape_configs:
  - job_name: ec2-instance
    static_configs:
      - targets:
          - localhost
        labels:
          job: apache2-logs
          instance: ec2-instance
          __path__: /var/log/apache2/*log
